package checksum

import (
	"crypto/md5"
	"crypto/sha1"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"hash/crc32"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// wantHex computes the expected digest from the standard library, so a wrong
// hash mapping in this package cannot agree with itself.
func wantHex(t *testing.T, k Kind, b []byte) string {
	t.Helper()
	switch k {
	case CRC32:
		return fmt.Sprintf("%08x", crc32.ChecksumIEEE(b))
	case MD5:
		s := md5.Sum(b)
		return hex.EncodeToString(s[:])
	case SHA1:
		s := sha1.Sum(b)
		return hex.EncodeToString(s[:])
	case SHA256:
		s := sha256.Sum256(b)
		return hex.EncodeToString(s[:])
	}
	t.Fatalf("no reference digest for kind %q", k)
	return ""
}

func writeFile(t *testing.T, dir, name string, content []byte) string {
	t.Helper()
	p := filepath.Join(dir, filepath.FromSlash(name))
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, content, 0o644); err != nil {
		t.Fatal(err)
	}
	return p
}

func TestParseSFVKeepsNamesWithSpaces(t *testing.T) {
	in := bom + "; Generated by WIN-SFV32 v1.1\r\n" +
		"\r\n" +
		"My Movie 2026.part1.rar 1A2B3C4D\r\n" +
		"sub/dir/second.r00\t00FF00ff\r\n"
	sums, err := ParseSFV(strings.NewReader(in))
	if err != nil {
		t.Fatal(err)
	}
	want := []Sum{
		{Name: "My Movie 2026.part1.rar", Kind: CRC32, Hex: "1a2b3c4d"},
		{Name: "sub/dir/second.r00", Kind: CRC32, Hex: "00ff00ff"},
	}
	if len(sums) != len(want) {
		t.Fatalf("got %d sums, want %d: %+v", len(sums), len(want), sums)
	}
	for i := range want {
		if sums[i] != want[i] {
			t.Errorf("sums[%d] = %+v, want %+v", i, sums[i], want[i])
		}
	}
}

func TestParseSFVRejectsMalformedLine(t *testing.T) {
	cases := map[string]string{
		"no crc at all":       "movie.rar\n",
		"crc is not hex":      "movie.rar ZZZZZZZZ\n",
		"crc is too short":    "movie.rar 1A2B3C\n",
		"empty name with crc": " 1a2b3c4d\n",
	}
	for name, in := range cases {
		t.Run(name, func(t *testing.T) {
			if sums, err := ParseSFV(strings.NewReader(in)); err == nil {
				t.Fatalf("ParseSFV(%q) = %+v, nil; want an error", in, sums)
			}
		})
	}
}

func TestParseHashFileInfersKindFromDigestLength(t *testing.T) {
	payload := []byte("knightloader")
	md5Hex := wantHex(t, MD5, payload)
	sha1Hex := wantHex(t, SHA1, payload)
	sha256Hex := wantHex(t, SHA256, payload)

	in := "# a comment\n" +
		md5Hex + "  plain name.bin\n" +
		strings.ToUpper(sha1Hex) + " *binary mode.bin\n" +
		sha256Hex + "\tsub/dir/deep.bin\n"
	sums, err := ParseHashFile(strings.NewReader(in))
	if err != nil {
		t.Fatal(err)
	}
	want := []Sum{
		{Name: "plain name.bin", Kind: MD5, Hex: md5Hex},
		{Name: "binary mode.bin", Kind: SHA1, Hex: sha1Hex},
		{Name: "sub/dir/deep.bin", Kind: SHA256, Hex: sha256Hex},
	}
	if len(sums) != len(want) {
		t.Fatalf("got %d sums, want %d: %+v", len(sums), len(want), sums)
	}
	for i := range want {
		if sums[i] != want[i] {
			t.Errorf("sums[%d] = %+v, want %+v", i, sums[i], want[i])
		}
	}
}

func TestParseHashFileRejectsMalformedLine(t *testing.T) {
	cases := map[string]string{
		"unsupported width": "deadbeefdead  file.bin\n",
		"not hex":           "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz  file.bin\n",
		"no file name":      "d41d8cd98f00b204e9800998ecf8427e\n",
		"empty file name":   "d41d8cd98f00b204e9800998ecf8427e  \n",
	}
	for name, in := range cases {
		t.Run(name, func(t *testing.T) {
			if sums, err := ParseHashFile(strings.NewReader(in)); err == nil {
				t.Fatalf("ParseHashFile(%q) = %+v, nil; want an error", in, sums)
			}
		})
	}
}

func TestFromNameExtractsCrc32Tag(t *testing.T) {
	tests := []struct {
		name string
		hex  string
		ok   bool
	}{
		{"Some.Release.1080p [ABCD1234].mkv", "abcd1234", true},
		{"movie.part1{CRC-ABCD1234}.rar", "abcd1234", true},
		{"movie.part1 {crc32_deadBEEF}.rar", "deadbeef", true},
		{"episode (0f1e2d3c).avi", "0f1e2d3c", true},
		// Several tags: the CRC is conventionally the last one.
		{"[Group] Show - 01 [1080p] [1a2b3c4d].mkv", "1a2b3c4d", true},
		{"plain.movie.mkv", "", false},
		{"Show (2026) 1080p.mkv", "", false},
		{"toolong [123456789].mkv", "", false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s, ok := FromName(tt.name)
			if ok != tt.ok {
				t.Fatalf("FromName(%q) ok = %v, want %v (got %+v)", tt.name, ok, tt.ok, s)
			}
			if !ok {
				return
			}
			if s.Hex != tt.hex || s.Kind != CRC32 || s.Name != tt.name {
				t.Fatalf("FromName(%q) = %+v, want name %q kind crc32 hex %q", tt.name, s, tt.name, tt.hex)
			}
		})
	}
}

func TestVerifyHashesFilesLargerThanTheReadBuffer(t *testing.T) {
	payload := make([]byte, 2*bufSize+1234)
	for i := range payload {
		payload[i] = byte(i * 31)
	}
	dir := t.TempDir()
	path := writeFile(t, dir, "big.bin", payload)

	for _, k := range []Kind{CRC32, MD5, SHA1, SHA256} {
		t.Run(string(k), func(t *testing.T) {
			ok, err := Verify(path, Sum{Name: "big.bin", Kind: k, Hex: wantHex(t, k, payload)})
			if err != nil {
				t.Fatal(err)
			}
			if !ok {
				t.Fatalf("Verify with the correct %s digest reported a mismatch", k)
			}
			ok, err = Verify(path, Sum{Name: "big.bin", Kind: k, Hex: wantHex(t, k, append(payload, 'x'))})
			if err != nil {
				t.Fatal(err)
			}
			if ok {
				t.Fatalf("Verify accepted a %s digest of different content", k)
			}
		})
	}
}

func TestVerifyIgnoresDigestCase(t *testing.T) {
	dir := t.TempDir()
	payload := []byte("case does not matter")
	path := writeFile(t, dir, "file.bin", payload)

	ok, err := Verify(path, Sum{Name: "file.bin", Kind: CRC32, Hex: strings.ToUpper(wantHex(t, CRC32, payload))})
	if err != nil {
		t.Fatal(err)
	}
	if !ok {
		t.Fatal("upper-case expected digest reported a mismatch")
	}
	if ok, err := Verify(path, Sum{Name: "file.bin", Kind: CRC32}); err != nil || ok {
		t.Fatalf("Verify with an empty digest = %v, %v; want false, nil", ok, err)
	}
}

func TestVerifyRejectsUnknownKind(t *testing.T) {
	dir := t.TempDir()
	path := writeFile(t, dir, "file.bin", []byte("x"))
	if _, err := Verify(path, Sum{Name: "file.bin", Kind: Kind("blake3"), Hex: "00"}); err == nil {
		t.Fatal("Verify accepted an unknown hash kind")
	}
}

func TestVerifyDirReportsMissingFileWithoutStoppingTheRun(t *testing.T) {
	dir := t.TempDir()
	good := []byte("volume one")
	bad := []byte("volume three, damaged in transit")
	writeFile(t, dir, "part1.rar", good)
	writeFile(t, dir, "sub/part3.rar", bad)

	sums := []Sum{
		{Name: "part1.rar", Kind: CRC32, Hex: wantHex(t, CRC32, good)},
		{Name: "part2.rar", Kind: CRC32, Hex: "deadbeef"},
		{Name: "sub/part3.rar", Kind: SHA256, Hex: wantHex(t, SHA256, []byte("volume three, intact"))},
	}
	res := VerifyDir(dir, sums)
	if len(res) != len(sums) {
		t.Fatalf("got %d results, want %d", len(res), len(sums))
	}
	if !res[0].OK || res[0].Err != nil {
		t.Errorf("present, matching file: %+v", res[0])
	}
	if res[1].Err == nil || !errors.Is(res[1].Err, os.ErrNotExist) {
		t.Errorf("missing file: Err = %v, want a not-exist error", res[1].Err)
	}
	if res[1].OK {
		t.Error("missing file reported OK")
	}
	// A mismatching file still reports what it hashed to.
	if res[2].OK || res[2].Err != nil || res[2].Got != wantHex(t, SHA256, bad) {
		t.Errorf("corrupt file: %+v", res[2])
	}
}

// TestVerifyDirRejectsPathEscape keeps a crafted .sfv from probing files
// outside the download folder.
func TestVerifyDirRejectsPathEscape(t *testing.T) {
	root := t.TempDir()
	secret := []byte("not yours")
	writeFile(t, root, "secret.txt", secret)
	dir := filepath.Join(root, "download")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}

	for _, name := range []string{"../secret.txt", `..\secret.txt`, "sub/../../secret.txt", ""} {
		res := VerifyDir(dir, []Sum{{Name: name, Kind: CRC32, Hex: wantHex(t, CRC32, secret)}})
		if len(res) != 1 {
			t.Fatalf("%q: got %d results, want 1", name, len(res))
		}
		if res[0].OK {
			t.Errorf("%q: escaping entry reported OK", name)
		}
		if !errors.Is(res[0].Err, errIllegalPath) {
			t.Errorf("%q: Err = %v, want errIllegalPath", name, res[0].Err)
		}
		if res[0].Got != "" {
			t.Errorf("%q: hashed a file outside the directory (Got = %q)", name, res[0].Got)
		}
	}
}

func TestVerifyDirAcceptsRelativeSubdirectory(t *testing.T) {
	dir := t.TempDir()
	payload := []byte("nested payload")
	writeFile(t, dir, "sub/dir/file.bin", payload)

	res := VerifyDir(dir, []Sum{
		{Name: "sub/dir/file.bin", Kind: MD5, Hex: wantHex(t, MD5, payload)},
		// A Windows-written entry for the same file.
		{Name: `sub\dir\file.bin`, Kind: MD5, Hex: wantHex(t, MD5, payload)},
	})
	for i, r := range res {
		if !r.OK || r.Err != nil {
			t.Errorf("res[%d] = %+v, want OK", i, r)
		}
	}
}
