// Regenerates src/flags.css: one inlined rule per flag the language menu can
// actually show.
//
// flag-icons ships ~270 flags. Importing the library would put every one of
// them in the bundle so the menu can show forty-two, and pointing at the
// package's own CSS would make the flags load as separate network requests
// that arrive after the menu has already painted. Inlining the subset as data
// URIs costs one rule per language and nothing at runtime.
//
// The list below is the SOURCE. Adding a language means adding its code here
// and re-running `node scripts/gen-flags.mjs` — hand-editing the generated CSS
// is how a language ends up in the picker with no flag beside it.
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { tmpdir } from 'node:os';
import { spawnSync } from 'node:child_process';

const here = dirname(fileURLToPath(import.meta.url));
const flagsDir = join(here, '..', 'node_modules', 'flag-icons', 'flags', '4x3');
const out = join(here, '..', 'src', 'flags.css');

// ISO 3166-1 alpha-2 region codes, in catalogue order. The three regional codes
// are deliberate: Catalan, Galician and Basque would otherwise all show the
// Spanish flag, which makes three entries of the menu indistinguishable.
const FLAGS = [
  'gb', 'de', 'fr', 'es', 'it', 'pt', 'nl', 'pl', 'ru', 'ua', 'cz', 'se', 'dk',
  'fi', 'no', 'tr', 'gr', 'hu', 'ro', 'jp', 'kr', 'cn', 'sa', 'il', 'th', 'vn',
  'bg', 'sk', 'si', 'hr', 'rs', 'lt', 'lv', 'ee', 'is', 'es-ct', 'es-ga',
  'es-pv', 'id', 'my', 'in', 'ir',
];

const head = `/* Generated by scripts/gen-flags.mjs — do not edit by hand.
   Only the flags the language menu offers, inlined so the build carries
   ${FLAGS.length} small rules instead of copying the whole flag-icons library. */
.fi { background-size: contain; background-position: 50%; background-repeat: no-repeat;
      display: inline-block; line-height: 1em; }
`;

// Heraldry is expensive: Serbia's flag is 181 kB of coat of arms on its own,
// Spain 81 kB, Croatia 31 kB. Minifying first roughly halves the sheet, and the
// flags are 16 px tall on screen so nothing of it is visible anyway. svgo is
// optional — a machine without it still gets a correct sheet, just a fatter
// one, rather than a build that refuses to run.
const tmp = await mkdtemp(join(tmpdir(), 'kl-flags-'));
const svgo = spawnSync('svgo', ['--version'], { shell: true, encoding: 'utf8' });
const minify = svgo.status === 0;
if (!minify) console.warn('svgo not found — flags will be inlined unminified');

let raw = 0;
let small = 0;
const rules = [];
for (const code of FLAGS) {
  const svg = await readFile(join(flagsDir, `${code}.svg`), 'utf8').catch(() => null);
  if (svg === null) {
    // Loud on purpose: a missing flag silently produces a blank box in the
    // menu, which reads as a broken build rather than as a missing file.
    console.error(`missing flag: ${code}.svg — is flag-icons installed?`);
    process.exit(1);
  }
  raw += svg.length;

  let out = svg;
  if (minify) {
    const f = join(tmp, `${code}.svg`);
    await writeFile(f, svg, 'utf8');
    const r = spawnSync('svgo', ['--quiet', '--multipass', f, '-o', f], { shell: true });
    // A flag svgo chokes on keeps its original bytes: a fatter rule is a far
    // better outcome than a blank flag in the menu.
    if (r.status === 0) out = await readFile(f, 'utf8').catch(() => svg);
  }
  small += out.length;

  const b64 = Buffer.from(out, 'utf8').toString('base64');
  rules.push(`.fi-${code} { background-image: url("data:image/svg+xml;base64,${b64}"); }`);
}
await rm(tmp, { recursive: true, force: true });

await writeFile(out, head + rules.join('\n') + '\n', 'utf8');
console.log(
  `wrote ${FLAGS.length} flags to src/flags.css — svg ${Math.round(raw / 1024)} kB` +
    (minify ? ` minified to ${Math.round(small / 1024)} kB` : ''),
);
