// Regenerates src/lib/glyphs.tsx from scripts/glyphs.json, GlimStone's
// reference/glyphs.json copied unchanged: one drawing per meaning, the same in
// every GlimStone app. Refresh the copy from GlimStone instead of editing it
// here, or the apps that share the set drift apart.
//
//   node scripts/gen-glyphs.mjs
//
// Using another glyph from the list means adding its name to USED and running
// this again. Drawings for meanings the list does not have stay in
// src/lib/icons.tsx.
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, 'glyphs.json');
const out = join(here, '..', 'src', 'lib', 'glyphs.tsx');

// In the order the list has them.
const USED = [
  'IconEye', 'IconEyeOff', 'IconRefresh', 'IconUpload', 'IconDownload', 'IconSearch',
  'IconPlay', 'IconPause', 'IconStop', 'IconPower', 'IconTrash', 'IconTrashFiles',
  'IconAdd', 'IconClose', 'IconPencil', 'IconCopy', 'IconCheck', 'IconLink', 'IconKey',
  'IconSignOut', 'IconInfo', 'IconHelp', 'IconMore', 'IconMenu', 'IconBack', 'IconForward',
  'IconLatest', 'IconFirst', 'IconMoveUp', 'IconMoveDown', 'IconExpand', 'IconCollapse',
  'IconSelectAll', 'IconClearSelection', 'IconFilter', 'IconPin', 'IconPriority', 'IconGrip',
  'IconExternalLink', 'IconWarning', 'IconBolt', 'IconCoffee', 'IconShieldOn', 'IconCode',
  'IconMoon', 'IconSun', 'IconGear', 'IconDashboard', 'IconFolder', 'IconFolderOpen',
  'IconFolderAdd', 'IconArchive', 'IconFleet', 'IconCollector', 'IconAccounts', 'IconNetwork',
  'IconPhone', 'IconBrowser', 'IconApp', 'IconModules', 'IconCaptcha', 'IconContainers',
  'IconGithub', 'IconTabGeneral', 'IconTabLook', 'IconTabSecurity', 'IconTabAdvanced',
  'IconTabApp', 'IconSchedules', 'IconNotifications', 'IconSliders', 'IconDiagnostics',
  'IconKeyboard', 'IconPaste', 'IconSort', 'IconFolderUp', 'IconHealth', 'IconQueued',
  'IconCaptchaTimer', 'IconResolvers',
];

// The centre line IconCheckDrawn traces through IconCheck, in IconCheck's
// coordinates. Each end runs past the round cap and the stroke is wider than
// the bar, so the finished trace uncovers the whole check.
const CHECK_TRACE = 'M0.54 6.54 5.3 11.3 13.39 2.07';
const CHECK_TRACE_WIDTH = '3.2';

const LICENCES = [
  [/^Streamline/, 'Streamline, free Core Solid (https://streamlinehq.com), CC BY 4.0'],
  [/^Font Awesome/, 'Font Awesome Free (https://fontawesome.com), CC BY 4.0'],
  [/^Tabler/, 'Tabler Icons (https://tabler.io/icons), MIT'],
  [/^Material Design Icons/, 'Material Design Icons (https://pictogrammers.com/library/mdi/), Apache 2.0'],
  [/^Simple Icons/, 'Simple Icons (https://simpleicons.org), CC0; the marks are trademarks, used only to name their owner'],
  [/^reCAPTCHA/, "reCAPTCHA's mark, a trademark used only where a captcha is the subject"],
];

const SHAPES = new Set(['path', 'rect', 'circle', 'ellipse']);
const CAMEL = { 'fill-rule': 'fillRule', 'clip-rule': 'clipRule' };

// The list spells markup the SVG way, wrapped in plain <g>s and with paint the
// <svg> already sets; this turns it into one JSX element per line.
function toJsx(markup, indent) {
  const lines = [];
  const kept = [];
  for (const [, close, tag, attrs] of markup.matchAll(/<(\/?)(\w+)([^>]*?)\s*\/?>/g)) {
    if (close) {
      if (!SHAPES.has(tag) && kept.pop()) lines.push(`${' '.repeat(indent + 2 * kept.filter(Boolean).length)}</${tag}>`);
      continue;
    }
    const props = [...attrs.matchAll(/([\w:-]+)="([^"]*)"/g)]
      .filter(([, name, value]) => !(name === 'fill' && value === 'currentColor') && name !== 'stroke-width')
      .map(([, name, value]) => `${CAMEL[name] ?? name}="${value}"`);
    if (tag === 'g' && props.length === 0) {
      kept.push(false);
      continue;
    }
    const pad = ' '.repeat(indent + 2 * kept.filter(Boolean).length);
    const shape = SHAPES.has(tag);
    lines.push(`${pad}<${[tag, ...props].join(' ')}${shape ? ' />' : '>'}`);
    if (!shape) kept.push(true);
  }
  return lines.join('\n');
}

const list = JSON.parse(await readFile(source, 'utf8'));
const byName = new Map(list.map((g) => [g.name, g]));
const glyphs = USED.map((name) => {
  const g = byName.get(name);
  if (!g) throw new Error(`${name} is not in ${source}`);
  return g;
});

const licences = LICENCES.filter(([pattern]) => glyphs.some((g) => pattern.test(g.source))).map(([, text]) => text);

const parts = [
  `// Generated by scripts/gen-glyphs.mjs from scripts/glyphs.json, GlimStone's
// list of one drawing per meaning. Change the generator or the list, not this
// file.
//
// Every glyph is a filled shape in the current colour, its gaps carved with
// evenodd. The drawings come from:
${licences.map((l) => `//   ${l}`).join('\n')}
// and the rest were drawn for GlimStone or KnightLoader.
import { useId, type SVGProps } from 'react';

/** The ink a drawing covers on its own grid: x, y, width and height. */
export type Ink = readonly [number, number, number, number];

/** The share of its box a glyph's ink spans; the rest is the air around it. */
const INK_SHARE = 0.75;

const round = (n: number) => Math.round(n * 1000) / 1000;

/**
 * glyph returns what every glyph's <svg> takes: 22px, the current colour and a
 * square viewBox around the centre of the ink, sized so that the ink's longer
 * side spans INK_SHARE of it. Glyphs drawn on different grids then read as one
 * size in one box.
 */
export function glyph([x, y, w, h]: Ink, p: SVGProps<SVGSVGElement>) {
  const side = Math.max(w, h) / INK_SHARE;
  return {
    width: 22,
    height: 22,
    viewBox: [x + (w - side) / 2, y + (h - side) / 2, side, side].map(round).join(' '),
    fill: 'currentColor',
    className: 'shrink-0',
    'aria-hidden': true,
    ...p,
  };
}
`,
];

for (const g of glyphs) {
  const ink = `[${g.ink.join(', ')}]`;
  parts.push(`/** ${g.means}: ${g.source}. */
export const ${g.name} = (p: SVGProps<SVGSVGElement>) => (
  <svg {...glyph(${ink}, p)}>
${toJsx(g.svg, 4)}
  </svg>
);
`);
  if (g.name === 'IconCheck') {
    parts.push(`/**
 * IconCheckDrawn is IconCheck drawing itself in, for a copy button's "Copied".
 * glim-check-draw animates a stroke, so the stroke runs along the check inside
 * a mask and uncovers the filled glyph as it goes. pathLength="1" lets the dash
 * offset run from 1 to 0 whatever the path's real length.
 */
export function IconCheckDrawn(p: SVGProps<SVGSVGElement>) {
  // useId has colons, which a url(#...) reference does not take in every browser.
  const mask = \`check\${useId().replace(/[^\\w-]/g, '')}\`;
  return (
    <svg {...glyph(${ink}, p)}>
      <mask id={mask}>
        <path
          className="glim-check-draw"
          pathLength="1"
          d="${CHECK_TRACE}"
          fill="none"
          stroke="white"
          strokeWidth="${CHECK_TRACE_WIDTH}"
          strokeLinejoin="round"
        />
      </mask>
      <g mask={\`url(#\${mask})\`}>
${toJsx(g.svg, 8)}
      </g>
    </svg>
  );
}
`);
  }
}

await writeFile(out, parts.join('\n'));
console.log(`wrote ${glyphs.length} glyphs to ${out}`);
