// Generated by scripts/gen-glyphs.mjs from GlimStone's reference/glyphs.json.
// Edit the generator or the list, not this file.
//
// Each glyph is GlimStone's drawing for one meaning, a filled shape whose gaps
// are carved with evenodd. The drawings come from:
//   Streamline, free Core Solid (https://streamlinehq.com), CC BY 4.0
//   Tabler Icons (https://tabler.io/icons), MIT
//   Material Design Icons (https://pictogrammers.com/library/mdi/), Apache 2.0
//   Simple Icons (https://simpleicons.org), CC0; the marks are trademarks, used only to name their owner
// and the rest were drawn for GlimStone or KnightLoader.
import Svg, { Path } from 'react-native-svg';

/**
 * GLYPH_BOX is the box a glyph gets beside a label, in points. Every labelled
 * button here is the key control, where GlimStone sets the glyph at 16 against
 * the 14 of an ordinary button.
 */
export const GLYPH_BOX = 16;

/**
 * GLYPH_INK is how much of its box a glyph's ink fills on its longer side. Air
 * around the ink keeps a glyph off the edge of the badge it sits in.
 */
export const GLYPH_INK = 0.8;

export interface GlyphProps {
  color: string;
  /** The box in points, or a share of the parent such as '100%'. */
  size?: number | string;
  /** Ink to the edge of the box, for a mark box that sizes its artwork to its
   *  own edges, as the README buttons do. */
  tight?: boolean;
}

// The list crops each viewBox square to the glyph's ink, so widening it around
// its centre leaves every glyph the same share of its box, whatever its grid.
function frame(viewBox: string, tight?: boolean): string {
  if (tight) return viewBox;
  const [x, y, side] = viewBox.split(' ').map(Number);
  const pad = (side / GLYPH_INK - side) / 2;
  return [x - pad, y - pad, side + 2 * pad, side + 2 * pad].join(' ');
}

/** Refresh, retry: Streamline interface-essential/arrow-round-left.svg. */
export function IconRefresh({ color, size = GLYPH_BOX, tight }: GlyphProps) {
  return (
    <Svg width={size} height={size} viewBox={frame('0.128 0.252 13.745 13.745', tight)} fill={color}>
      <Path fillRule="evenodd" d="M5.35099 1.00245c0 -0.303349 -0.18273 -0.576826 -0.46299 -0.692912 -0.28026 -0.116085 -0.60284 -0.051918 -0.81734 0.16258L1.67164 2.87114c-0.2929 0.29289 -0.2929 0.76777 0 1.06066l2.39902 2.39902c0.2145 0.2145 0.53708 0.27867 0.81734 0.16258 0.28026 -0.11608 0.46299 -0.38956 0.46299 -0.69291V4.40137h1.64902c2.0976 0 3.79809 1.70045 3.79809 3.79805 0 2.09758 -1.70049 3.79808 -3.79809 3.79808S3.20197 10.297 3.20197 8.19942c0 -0.55229 -0.44772 -1 -1 -1 -0.55229 0 -1 0.44771 -1 1 0 3.20218 2.59587 5.79808 5.79804 5.79808 3.20219 0 5.79809 -2.5959 5.79809 -5.79808 0 -3.20217 -2.5959 -5.79805 -5.79809 -5.79805H5.35099V1.00245Z" clipRule="evenodd" />
    </Svg>
  );
}

/** Start, run now: Streamline entertainment/button-play.svg. */
export function IconPlay({ color, size = GLYPH_BOX, tight }: GlyphProps) {
  return (
    <Svg width={size} height={size} viewBox={frame('0.01 0.019 13.981 13.981', tight)} fill={color}>
      <Path fillRule="evenodd" d="M2.67593 0.019165c-0.29576 0 -0.58657 0.0753875 -0.84499 0.218948 -0.26314 0.134139 -0.48525 0.336896 -0.64277 0.58693 -0.15979 0.253627 -0.247004 0.546207 -0.252169 0.845927l-0.000075 0V12.3396H0.935852l0.000149 0.0086c0.005165 0.2997 0.092379 0.5923 0.252169 0.8459 0.15752 0.2501 0.37963 0.4528 0.64277 0.587 0.25842 0.1435 0.54923 0.2189 0.84499 0.2189 0.29995 0 0.59481 -0.0775 0.85596 -0.2251 0.00575 -0.0032 0.01143 -0.0066 0.01704 -0.0101l8.62977 -5.33745c0.2617 -0.13189 0.4826 -0.33282 0.6388 -0.5813 0.1611 -0.25659 0.2467 -0.55345 0.2467 -0.85647 0 -0.30301 -0.0856 -0.59988 -0.2467 -0.85646 -0.1563 -0.24874 -0.3776 -0.44984 -0.6396 -0.58172L3.54751 0.253465c-0.00515 -0.00316 -0.01036 -0.006227 -0.01562 -0.009199 -0.26115 -0.1475588 -0.55601 -0.225101 -0.85596 -0.225101Z" clipRule="evenodd" />
    </Svg>
  );
}

/** Stop, abort: Streamline entertainment/button-stop.svg. */
export function IconStop({ color, size = GLYPH_BOX, tight }: GlyphProps) {
  return (
    <Svg width={size} height={size} viewBox={frame('0 0 14 14', tight)} fill={color}>
      <Path fillRule="evenodd" d="M1.5 0C0.671573 0 0 0.671573 0 1.5v11c0 0.8284 0.671573 1.5 1.5 1.5h11c0.8284 0 1.5 -0.6716 1.5 -1.5v-11c0 -0.828427 -0.6716 -1.5 -1.5 -1.5h-11Z" clipRule="evenodd" />
    </Svg>
  );
}

/** Power on and off: Streamline entertainment/button-power-1.svg. */
export function IconPower({ color, size = GLYPH_BOX, tight }: GlyphProps) {
  return (
    <Svg width={size} height={size} viewBox={frame('0 0 14 14', tight)} fill={color}>
      <Path fillRule="evenodd" d="M8 1c0 -0.552285 -0.44772 -1 -1 -1S6 0.447715 6 1v5.07692c0 0.55229 0.44772 1 1 1s1 -0.44771 1 -1V1ZM3.92308 3.05886c0.43532 -0.33987 0.51271 -0.96829 0.17284 -1.40361 -0.33987 -0.43533 -0.96829 -0.51271 -1.40361 -0.17285C1.54339 2.37939 0.703135 3.61265 0.288786 5.01012 -0.125563 6.40758 -0.0933357 7.89953 0.38097 9.27781 0.855276 10.6561 1.748 11.8519 2.93458 12.6984 4.12116 13.545 5.5424 14 7 14c1.4576 0 2.87884 -0.455 4.0654 -1.3016 1.1866 -0.8465 2.0793 -2.0423 2.5536 -3.42059 0.4743 -1.37827 0.5066 -2.87023 0.0922 -4.26769 -0.4143 -1.39747 -1.2546 -2.63073 -2.4035 -3.52772 -0.4353 -0.33986 -1.0638 -0.26248 -1.40362 0.17285 -0.33987 0.43532 -0.26248 1.06374 0.17282 1.40361 0.8207 0.6407 1.4209 1.5216 1.7168 2.51979 0.296 0.99819 0.273 2.06387 -0.0658 3.04835s-0.9765 1.8386 -1.82403 2.4433C9.05632 11.675 8.04114 12 7 12s-2.05632 -0.325 -2.90387 -0.9297c-0.84756 -0.6047 -1.48522 -1.45882 -1.82401 -2.4433 -0.33879 -0.98448 -0.36181 -2.05016 -0.06584 -3.04835 0.29596 -0.99819 0.89614 -1.87909 1.7168 -2.51979Z" clipRule="evenodd" />
    </Svg>
  );
}

/** Delete: Streamline interface-essential/recycle-bin-2.svg. */
export function IconTrash({ color, size = GLYPH_BOX, tight }: GlyphProps) {
  return (
    <Svg width={size} height={size} viewBox={frame('0 0 14 14', tight)} fill={color}>
      <Path fillRule="evenodd" d="M5.76256 2.01256C6.09075 1.68437 6.53587 1.5 7 1.5c0.46413 0 0.90925 0.18437 1.23744 0.51256 0.20736 0.20737 0.35731 0.46141 0.43961 0.73744h-3.3541c0.0823 -0.27603 0.23225 -0.53007 0.43961 -0.73744ZM3.78868 2.75c0.10537 -0.67679 0.42285 -1.30773 0.91322 -1.798097C5.3114 0.34241 6.13805 0 7 0c0.86195 0 1.6886 0.34241 2.2981 0.951903 0.49037 0.490367 0.8079 1.121307 0.9132 1.798097H13c0.4142 0 0.75 0.33579 0.75 0.75 0 0.41422 -0.3358 0.75 -0.75 0.75h-1v8.25c0 0.3978 -0.158 0.7794 -0.4393 1.0607S10.8978 14 10.5 14h-7c-0.39783 0 -0.77936 -0.158 -1.06066 -0.4393C2.15804 13.2794 2 12.8978 2 12.5V4.25H1c-0.414214 0 -0.75 -0.33578 -0.75 -0.75 0 -0.41421 0.335786 -0.75 0.75 -0.75h2.78868ZM5 5.87646c0.34518 0 0.625 0.27983 0.625 0.625V10.503c0 0.3451 -0.27982 0.625 -0.625 0.625s-0.625 -0.2799 -0.625 -0.625V6.50146c0 -0.34517 0.27982 -0.625 0.625 -0.625Zm4.625 0.625c0 -0.34517 -0.27982 -0.625 -0.625 -0.625s-0.625 0.27983 -0.625 0.625V10.503c0 0.3451 0.27982 0.625 0.625 0.625s0.625 -0.2799 0.625 -0.625V6.50146Z" clipRule="evenodd" />
    </Svg>
  );
}

/** Add: Drawn for GlimStone. */
export function IconAdd({ color, size = GLYPH_BOX, tight }: GlyphProps) {
  return (
    <Svg width={size} height={size} viewBox={frame('0.006 0.006 13.988 13.988', tight)} fill={color}>
      <Path fillRule="evenodd" d="M5.756 12.873 L5.774 12.994 L5.845 13.228 L5.961 13.444 L6.034 13.543 L6.207 13.716 L6.411 13.852 L6.522 13.905 L6.756 13.976 L6.877 13.994 L7.123 13.994 L7.244 13.976 L7.478 13.905 L7.694 13.789 L7.793 13.716 L7.966 13.543 L8.102 13.339 L8.155 13.228 L8.226 12.994 L8.25 12.75 L8.25 8.25 L12.75 8.25 L12.994 8.226 L13.228 8.155 L13.444 8.039 L13.543 7.966 L13.716 7.793 L13.789 7.694 L13.905 7.478 L13.976 7.244 L13.994 7.123 L13.994 6.877 L13.976 6.756 L13.905 6.522 L13.789 6.306 L13.634 6.116 L13.444 5.961 L13.228 5.845 L12.994 5.774 L12.75 5.75 L8.25 5.75 L8.25 1.25 L8.226 1.006 L8.155 0.772 L8.039 0.556 L7.884 0.366 L7.793 0.284 L7.589 0.148 L7.478 0.095 L7.363 0.054 L7.123 0.006 L6.877 0.006 L6.637 0.054 L6.411 0.148 L6.306 0.211 L6.116 0.366 L5.961 0.556 L5.845 0.772 L5.774 1.006 L5.75 1.25 L5.75 5.75 L1.25 5.75 L1.006 5.774 L0.887 5.804 L0.661 5.898 L0.556 5.961 L0.366 6.116 L0.211 6.306 L0.148 6.411 L0.054 6.637 L0.006 6.877 L0.006 7.123 L0.054 7.363 L0.148 7.589 L0.284 7.793 L0.457 7.966 L0.661 8.102 L0.772 8.155 L1.006 8.226 L1.25 8.25 L5.75 8.25Z" />
    </Svg>
  );
}

/** Close, cancel: Drawn for GlimStone. */
export function IconClose({ color, size = GLYPH_BOX, tight }: GlyphProps) {
  return (
    <Svg width={size} height={size} viewBox={frame('0 0 14 14', tight)} fill={color}>
      <Path fillRule="evenodd" d="M11.957 13.716 L12.056 13.789 L12.272 13.905 L12.506 13.976 L12.75 14 L12.994 13.976 L13.228 13.905 L13.444 13.789 L13.543 13.716 L13.716 13.543 L13.789 13.444 L13.905 13.228 L13.976 12.994 L14 12.75 L13.976 12.506 L13.905 12.272 L13.852 12.161 L13.789 12.056 L13.634 11.866 L8.768 7 L13.716 2.043 L13.789 1.944 L13.905 1.728 L13.976 1.494 L14 1.25 L13.976 1.006 L13.905 0.772 L13.789 0.556 L13.716 0.457 L13.543 0.284 L13.339 0.148 L13.113 0.054 L12.873 0.006 L12.627 0.006 L12.387 0.054 L12.272 0.095 L12.056 0.211 L11.866 0.366 L7 5.232 L2.043 0.284 L1.839 0.148 L1.613 0.054 L1.494 0.024 L1.25 0 L1.127 0.006 L0.887 0.054 L0.661 0.148 L0.457 0.284 L0.284 0.457 L0.211 0.556 L0.095 0.772 L0.024 1.006 L0 1.25 L0.024 1.494 L0.095 1.728 L0.211 1.944 L0.366 2.134 L5.232 7 L0.284 11.957 L0.211 12.056 L0.095 12.272 L0.024 12.506 L0 12.75 L0.024 12.994 L0.095 13.228 L0.211 13.444 L0.284 13.543 L0.457 13.716 L0.661 13.852 L0.772 13.905 L1.006 13.976 L1.25 14 L1.494 13.976 L1.728 13.905 L1.944 13.789 L2.134 13.634 L7 8.768Z" />
    </Svg>
  );
}

/** Copy: Tabler Icons, filled copy (MIT). */
export function IconCopy({ color, size = GLYPH_BOX, tight }: GlyphProps) {
  return (
    <Svg width={size} height={size} viewBox={frame('2 2 20 20', tight)} fill={color}>
      <Path d="M20.926 7.074a3.67 3.67 0 0 1 1.074 2.593v8.666a3.667 3.667 0 0 1 -3.667 3.667h-8.666a3.667 3.667 0 0 1 -3.667 -3.667v-8.666q 0 -.053 .005 -.102a3.66 3.66 0 0 1 3.662 -3.565h8.666c.973 0 1.905 .386 2.593 1.074" />
      <Path d="M17.374 3.514a1 1 0 1 1 -1.748 .972c-.221 -.398 -.342 -.486 -.626 -.486h-10c-.548 0 -1 .452 -1 1v9.998c0 .36 .194 .692 .507 .87a1 1 0 1 1 -.99 1.738a3 3 0 0 1 -1.517 -2.606v-10c0 -1.652 1.348 -3 3 -3h10c1.094 0 1.828 .533 2.374 1.514" />
    </Svg>
  );
}

/** Verify, confirmed: Drawn for GlimStone. */
export function IconCheck({ color, size = GLYPH_BOX, tight }: GlyphProps) {
  return (
    <Svg width={size} height={size} viewBox={frame('0.3 0.549 13.399 13.399', tight)} fill={color}>
      <Path fillRule="evenodd" d="M4.381 12.219 L4.574 12.378 L4.793 12.497 L5.032 12.572 L5.155 12.592 L5.405 12.596 L5.651 12.552 L5.884 12.461 L6.096 12.328 L6.278 12.157 L13.457 3.957 L13.584 3.736 L13.666 3.495 L13.699 3.242 L13.683 2.988 L13.656 2.863 L13.566 2.625 L13.431 2.408 L13.257 2.222 L13.05 2.074 L12.936 2.016 L12.695 1.934 L12.442 1.901 L12.188 1.917 L11.942 1.983 L11.713 2.096 L11.511 2.251 L5.238 9.399 L2.519 6.681 L2.425 6.595 L2.213 6.454 L1.977 6.356 L1.854 6.325 L1.6 6.3 L1.346 6.325 L1.223 6.356 L0.987 6.454 L0.775 6.595 L0.595 6.775 L0.454 6.987 L0.399 7.103 L0.325 7.346 L0.3 7.6 L0.306 7.727 L0.356 7.977 L0.399 8.097 L0.519 8.322 L0.681 8.519Z" />
    </Svg>
  );
}

/** Connect, pair: Streamline interface-essential/link-chain.svg. */
export function IconLink({ color, size = GLYPH_BOX, tight }: GlyphProps) {
  return (
    <Svg width={size} height={size} viewBox={frame('0 0 14 14', tight)} fill={color}>
      <Path fillRule="evenodd" d="m7.6715 2.7426 -0.00004 0.00004 -0.96431 0.96443c-0.3905 0.39054 -1.02367 0.39058 -1.41422 0.00008 -0.39054 -0.3905 -0.39058 -1.02367 -0.00008 -1.41422l0.96436 -0.96446 0.00004 -0.00004c1.77124 -1.771239 4.64295 -1.771239 6.41425 0 1.7712 1.77122 1.7712 4.64293 0 6.41417l0 0.00004 -0.9644 0.96443c-0.3905 0.39054 -1.0236 0.39058 -1.4142 0.00008 -0.39051 -0.39051 -0.39055 -1.02367 0 -1.41422l0.9643 -0.96446 0 -0.00004c0.9902 -0.99019 0.9902 -2.5956 0 -3.58579 -0.9901 -0.99017 -2.59551 -0.99019 -3.5857 -0.00004ZM3.70696 5.29285c0.39054 0.3905 0.39058 1.02367 0.00008 1.41422l-0.96436 0.96446 -0.00004 0.00004c-0.99019 0.99019 -0.99019 2.59563 0 3.58583 0.99018 0.9901 2.59555 0.9901 3.58575 0l0.00004 0 0.96431 -0.9645c0.3905 -0.39051 1.02367 -0.39055 1.41422 0 0.39054 0.3905 0.39058 1.0236 0.00008 1.4142l-0.96436 0.9644 -0.00004 0.0001c-1.77124 1.7712 -4.64298 1.7712 -6.41421 0 -1.771226 -1.7713 -1.771239 -4.64296 -0.00004 -6.4142l0.00004 -0.00004 0.96431 -0.96443c0.3905 -0.39054 1.02367 -0.39058 1.41422 -0.00008Zm5.50015 0.91426c0.39052 -0.39053 0.39052 -1.02369 0 -1.41422 -0.39053 -0.39052 -1.02369 -0.39052 -1.41422 0l-3 3c-0.39052 0.39053 -0.39052 1.02369 0 1.41422 0.39053 0.39052 1.02369 0.39052 1.41422 0l3 -3Z" clipRule="evenodd" />
    </Svg>
  );
}

/** Information: Streamline interface-essential/information-circle.svg. */
export function IconInfo({ color, size = GLYPH_BOX, tight }: GlyphProps) {
  return (
    <Svg width={size} height={size} viewBox={frame('0 0 14 14', tight)} fill={color}>
      <Path fillRule="evenodd" d="M7 14c3.866 0 7 -3.134 7 -7 0 -3.86599 -3.134 -7 -7 -7 -3.86599 0 -7 3.13401 -7 7 0 3.866 3.13401 7 7 7ZM5.5 9.375c-0.34518 0 -0.625 0.27982 -0.625 0.625 0 0.3452 0.27982 0.625 0.625 0.625h3c0.34518 0 0.625 -0.2798 0.625 -0.625 0 -0.34518 -0.27982 -0.625 -0.625 -0.625h-0.875V6.5c0 -0.34518 -0.27982 -0.625 -0.625 -0.625H6c-0.34518 0 -0.625 0.27982 -0.625 0.625s0.27982 0.625 0.625 0.625h0.375v2.25H5.5ZM8 4c0 0.55228 -0.44772 1 -1 1s-1 -0.44772 -1 -1 0.44772 -1 1 -1 1 0.44772 1 1Z" clipRule="evenodd" />
    </Svg>
  );
}

/** Back: KnightLoader's drawing on a 20-unit grid. */
export function IconBack({ color, size = GLYPH_BOX, tight }: GlyphProps) {
  return (
    <Svg width={size} height={size} viewBox={frame('4.25 3.6 12.8 12.8', tight)} fill={color}>
      <Path d="M6.6 10 13 3.6l1.7 1.7L10 10l4.7 4.7-1.7 1.7L6.6 10Z" />
    </Svg>
  );
}

/** Expand: KnightLoader's drawing on a 20-unit grid. */
export function IconExpand({ color, size = GLYPH_BOX, tight }: GlyphProps) {
  return (
    <Svg width={size} height={size} viewBox={frame('3.6 2.95 12.8 12.8', tight)} fill={color}>
      <Path d="M10 13.4 3.6 7l1.7-1.7L10 10l4.7-4.7L16.4 7 10 13.4Z" />
    </Svg>
  );
}

/** Collapse: KnightLoader's drawing on a 20-unit grid. */
export function IconCollapse({ color, size = GLYPH_BOX, tight }: GlyphProps) {
  return (
    <Svg width={size} height={size} viewBox={frame('3.6 4.25 12.8 12.8', tight)} fill={color}>
      <Path d="M10 6.6 16.4 13l-1.7 1.7L10 10l-4.7 4.7L3.6 13 10 6.6Z" />
    </Svg>
  );
}

/** Write to us: Streamline mail/mail-send-envelope.svg. */
export function IconMail({ color, size = GLYPH_BOX, tight }: GlyphProps) {
  return (
    <Svg width={size} height={size} viewBox={frame('0 0 14 14', tight)} fill={color}>
      <Path fillRule="evenodd" d="M0 2.75a1.5 1.5 0 0 1 1.5 -1.5h11a1.5 1.5 0 0 1 1.5 1.5v0.342L7.383 7.504A0.72 0.72 0 0 1 7 7.607a0.72 0.72 0 0 1 -0.383 -0.103L0 3.092V2.75Zm0 1.844v6.656a1.5 1.5 0 0 0 1.5 1.5h11a1.5 1.5 0 0 0 1.5 -1.5V4.594L8.073 8.546l-0.005 0.004A1.966 1.966 0 0 1 7 8.857c-0.375 0 -0.753 -0.102 -1.068 -0.307l-0.005 -0.004L0 4.594Z" clipRule="evenodd" />
    </Svg>
  );
}

/** Settings: Streamline interface-essential/cog.svg. */
export function IconGear({ color, size = GLYPH_BOX, tight }: GlyphProps) {
  return (
    <Svg width={size} height={size} viewBox={frame('-0.001 0 14 14', tight)} fill={color}>
      <Path fillRule="evenodd" d="m5.557 0.69 -0.463 1.195 -1.594 0.904 -1.27 -0.194a1.077 1.077 0 0 0 -1.078 0.528l-0.43 0.754a1.077 1.077 0 0 0 0.086 1.217l0.807 1.001v1.81L0.83 8.906a1.077 1.077 0 0 0 -0.086 1.217l0.43 0.754a1.077 1.077 0 0 0 1.078 0.528l1.27 -0.194 1.573 0.904 0.463 1.196a1.076 1.076 0 0 0 1 0.689h0.905a1.076 1.076 0 0 0 1.002 -0.69l0.463 -1.195 1.572 -0.904 1.27 0.194a1.077 1.077 0 0 0 1.078 -0.528l0.43 -0.754a1.077 1.077 0 0 0 -0.086 -1.217l-0.807 -1.001v-1.81l0.786 -1.001a1.077 1.077 0 0 0 0.086 -1.217l-0.43 -0.754a1.076 1.076 0 0 0 -1.078 -0.528l-1.27 0.194 -1.573 -0.904L8.443 0.689A1.077 1.077 0 0 0 7.442 0h-0.884a1.077 1.077 0 0 0 -1.001 0.69ZM7 9.25a2.25 2.25 0 1 0 0 -4.5 2.25 2.25 0 0 0 0 4.5Z" clipRule="evenodd" />
    </Svg>
  );
}

/** A folder: Streamline interface-essential/new-folder.svg. */
export function IconFolder({ color, size = GLYPH_BOX, tight }: GlyphProps) {
  return (
    <Svg width={size} height={size} viewBox={frame('0 0 14 14', tight)} fill={color}>
      <Path d="M6.12675 0.805269c-0.2708 -0.205804 -0.60343 -0.313418 -0.9433 -0.305333H1.5c-0.39782 0 -0.779356 0.158035 -1.06066 0.43934C0.158035 1.22058 0 1.60211 0 1.99994v9.99996c0 0.3979 0.158035 0.7794 0.43934 1.0607 0.281304 0.2813 0.66283 0.4393 1.06066 0.4393h11c0.3978 0 0.7794 -0.158 1.0607 -0.4393S14 12.3978 14 11.9999V3.99994c0 -0.39783 -0.158 -0.77936 -0.4393 -1.06066 -0.2813 -0.28131 -0.6629 -0.43934 -1.0607 -0.43934H6.89039l-0.21495 -0.85979c-0.08224 -0.33249 -0.27599 -0.62762 -0.54869 -0.834881Z" />
    </Svg>
  );
}

/** Docker containers: Simple Icons whale (CC0, a trademark used descriptively). */
export function IconContainers({ color, size = GLYPH_BOX, tight }: GlyphProps) {
  return (
    <Svg width={size} height={size} viewBox={frame('0 0 24 24', tight)} fill={color}>
      <Path d="M13.983 11.078h2.119a.186.186 0 00.186-.185V9.006a.186.186 0 00-.186-.186h-2.119a.185.185 0 00-.185.185v1.888c0 .102.083.185.185.185m-2.954-5.43h2.118a.186.186 0 00.186-.186V3.574a.186.186 0 00-.186-.185h-2.118a.185.185 0 00-.185.185v1.888c0 .102.082.185.185.185m0 2.716h2.118a.187.187 0 00.186-.186V6.29a.186.186 0 00-.186-.185h-2.118a.185.185 0 00-.185.185v1.887c0 .102.082.185.185.186m-2.93 0h2.12a.186.186 0 00.184-.186V6.29a.185.185 0 00-.185-.185H8.1a.185.185 0 00-.185.185v1.887c0 .102.083.185.185.186m-2.964 0h2.119a.186.186 0 00.185-.186V6.29a.185.185 0 00-.185-.185H5.136a.186.186 0 00-.186.185v1.887c0 .102.084.185.186.186m5.893 2.715h2.118a.186.186 0 00.186-.185V9.006a.186.186 0 00-.186-.186h-2.118a.185.185 0 00-.185.185v1.888c0 .102.082.185.185.185m-2.93 0h2.12a.185.185 0 00.184-.185V9.006a.185.185 0 00-.184-.186h-2.12a.185.185 0 00-.184.185v1.888c0 .102.083.185.185.185m-2.964 0h2.119a.185.185 0 00.185-.185V9.006a.185.185 0 00-.184-.186h-2.12a.186.186 0 00-.186.186v1.887c0 .102.084.185.186.185m-2.92 0h2.12a.185.185 0 00.184-.185V9.006a.185.185 0 00-.184-.186h-2.12a.185.185 0 00-.184.185v1.888c0 .102.082.185.185.185M23.763 9.89c-.065-.051-.672-.51-1.954-.51-.338.001-.676.03-1.01.087-.248-1.7-1.653-2.53-1.716-2.566l-.344-.199-.226.327c-.284.438-.49.922-.612 1.43-.23.97-.09 1.882.403 2.661-.595.332-1.55.413-1.744.42H.751a.751.751 0 00-.75.748 11.376 11.376 0 00.692 4.062c.545 1.428 1.355 2.48 2.41 3.124 1.18.723 3.1 1.137 5.275 1.137.983.003 1.963-.086 2.93-.266a12.248 12.248 0 003.823-1.389c.98-.567 1.86-1.288 2.61-2.136 1.252-1.418 1.998-2.997 2.553-4.4h.221c1.372 0 2.215-.549 2.68-1.009.309-.293.55-.65.707-1.046l.098-.288Z" />
    </Svg>
  );
}

/** The GitHub repository: Simple Icons github (CC0, a trademark used descriptively). */
export function IconGithub({ color, size = GLYPH_BOX, tight }: GlyphProps) {
  return (
    <Svg width={size} height={size} viewBox={frame('0 0 24 24', tight)} fill={color}>
      <Path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12" />
    </Svg>
  );
}

/** Paste: Streamline interface-essential/empty-clipboard.svg. */
export function IconPaste({ color, size = GLYPH_BOX, tight }: GlyphProps) {
  return (
    <Svg width={size} height={size} viewBox={frame('0 0 14 14', tight)} fill={color}>
      <Path fillRule="evenodd" d="M5.5 0c-0.55228 0 -1 0.447716 -1 1v0.5c0 0.55229 0.44772 1 1 1h3c0.55229 0 1 -0.44771 1 -1V1c0 -0.552285 -0.44771 -1 -1 -1h-3ZM2.75 1h0.5v0.5c0 1.24264 1.00736 2.25 2.25 2.25h3c1.24264 0 2.25 -1.00736 2.25 -2.25V1h0.5c0.8284 0 1.5 0.67157 1.5 1.5v10c0 0.8284 -0.6716 1.5 -1.5 1.5h-8.5c-0.82843 0 -1.5 -0.6716 -1.5 -1.5v-10c0 -0.82843 0.67157 -1.5 1.5 -1.5Z" clipRule="evenodd" />
    </Svg>
  );
}

/** Write to us, under the pointer or a finger: Material Design Icons email-open (Apache 2.0). */
export function IconMailOpen({ color, size = GLYPH_BOX, tight }: GlyphProps) {
  return (
    <Svg width={size} height={size} viewBox={frame('2 0.32 20 20', tight)} fill={color}>
      <Path d="M4,8L12,13L20,8V8L12,3L4,8V8M22,8V18A2,2 0 0,1 20,20H4A2,2 0 0,1 2,18V8C2,7.27 2.39,6.64 2.97,6.29L12,0.64L21.03,6.29C21.61,6.64 22,7.27 22,8Z" />
    </Svg>
  );
}
