package debrid

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/junkerderprovinz/knightloader/internal/httpx"
)

// DebridLink speaks the Debrid-Link v2 API.
//
// VERIFIED, NOT GUESSED - every path, header and field name below was read off
// Debrid-Link's own documentation at https://debrid-link.com/api_doc/v2
// (fetched 2026-09-06), the same standard internal/hosterauth's JD client
// holds itself to:
//
//   - "API URL: https://debrid-link.com/api/v2", and authentication is
//     "Authorization: Bearer [token]" where the token may be "a Private API key
//     generated by the user" at https://debrid-link.com/webapp/apikey - which
//     is exactly what a KindAPIKey catalogue entry stores.
//   - The envelope is {"success": true, "value": ...} on success and
//     {"success": false, "error": "badToken"} with an HTTP status in the
//     400/500 range on failure. The error is a CODE, not a sentence, and the
//     documented list ("List API errors") is what errorText below translates.
//   - GET /downloader/hosts answers [{name, type, status, isFree, domains[],
//     regexs[]}] and states the rule this file applies: "Host is online when
//     the 'status' >= 1".
//   - POST /downloader/add takes url (required) and password (optional) and
//     answers the link object {created, id, name, url, downloadUrl, expired,
//     chunk, host, size}. Its own note - "In most case the result is an
//     associative array (link object), but it can be an sequential array when
//     you send a folder that have multiple links" - is why Unlock decodes into
//     a RawMessage and tries both shapes rather than assuming the object.
//   - GET /account/infos answers {username, accountType, premiumLeft, pts, …}.
//   - GET /downloader/limits answers {usagePercent: {current, value},
//     nextResetSeconds: {current, value}, hosters: [...]}.
//
// This is the service jdp could not get working through JDownloader (2026-09-06:
// "ich habe debrid-link.com hinzugefügt aber es lädt rapidgator links nicht
// herunter. wenn ich mich in JD mit dem account anmelde kommt ein fenster wo ich
// das gerät bestätigen muss. das kam hier nicht"). That window is Debrid-Link's
// OAuth2 device flow, which JD's own plugin drives and KnightLoader never shows
// because it never shows JD's interface at all - so the login could only ever
// come back "JDownloader could not validate this login", which is exactly what
// the instance reported. A private API key needs no device confirmation, so this
// path has no such step to miss.
type DebridLink struct {
	key  string
	base string
	hc   *http.Client
}

func NewDebridLink(key string) *DebridLink {
	return &DebridLink{
		key:  key,
		base: "https://debrid-link.com/api/v2",
		hc:   httpx.New(httpx.Options{Timeout: 30 * time.Second}),
	}
}

func (*DebridLink) ID() string    { return "debridlink" }
func (*DebridLink) Label() string { return "Debrid-Link" }

// dlEnvelope is the uniform wrapper every v2 answer carries. Error is a code
// from the documented table, never a sentence - see errorText.
type dlEnvelope struct {
	Success bool            `json:"success"`
	Value   json.RawMessage `json:"value"`
	Error   string          `json:"error"`
}

func (d *DebridLink) get(ctx context.Context, path string, out any) error {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, d.base+path, nil)
	if err != nil {
		return err
	}
	return d.send(req, path, out)
}

// postJSON sends a JSON body, which is what the documentation asks for in so
// many words: "The request body are sent in JSON."
func (d *DebridLink) postJSON(ctx context.Context, path string, body any, out any) error {
	raw, err := json.Marshal(body)
	if err != nil {
		return err
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, d.base+path, bytes.NewReader(raw))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")
	return d.send(req, path, out)
}

// send performs the call and unwraps the envelope. Both halves matter: an HTTP
// error carries a body worth reading (the error code lives there, not in the
// status line), and a 200 can still be success:false.
func (d *DebridLink) send(req *http.Request, path string, out any) error {
	if d.key != "" {
		req.Header.Set("Authorization", "Bearer "+d.key)
	}
	req.Header.Set("Accept", "application/json")
	resp, err := d.hc.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(io.LimitReader(resp.Body, 8<<20))
	var env dlEnvelope
	if err := json.Unmarshal(raw, &env); err != nil {
		return fmt.Errorf("debrid-link %s: %s", path, resp.Status)
	}
	if !env.Success {
		return fmt.Errorf("debrid-link %s: %s", path, errorText(env.Error))
	}
	if out != nil && len(env.Value) > 0 {
		return json.Unmarshal(env.Value, out)
	}
	return nil
}

// errorText turns one of the documented error codes into a sentence a person
// can act on, and leaves anything else exactly as the service said it. Only
// the codes this client can actually provoke are translated - the seedbox and
// OAuth halves of that table are not reachable from here.
func errorText(code string) string {
	switch code {
	case "badToken":
		return "the API key was refused - generate a new one at debrid-link.com/webapp/apikey"
	case "hidedToken":
		return "this API key is not enabled yet - confirm it in your Debrid-Link account"
	case "notDebrid":
		return "Debrid-Link could not unlock this link; the hoster may be down"
	case "hostNotValid":
		return "Debrid-Link does not support this file hoster"
	case "fileNotFound":
		return "the hoster says this file is gone"
	case "fileNotAvailable":
		return "the hoster says this file is temporarily unavailable"
	case "badFilePassword":
		return "this link needs a password, and the one given was wrong or missing"
	case "notFreeHost":
		return "this hoster is not available on a free Debrid-Link account"
	case "maintenanceHost":
		return "this hoster is in maintenance at Debrid-Link"
	case "maxLink", "maxLinkHost":
		return "the daily link limit for this account is used up"
	case "maxData", "maxDataHost":
		return "the daily traffic limit for this account is used up"
	case "serverNotAllowed":
		return "Debrid-Link refuses requests from this server or VPN; contact them to allow it"
	case "floodDetected":
		return "too many requests - Debrid-Link rate-limited this account, try again in an hour"
	case "":
		return "the call failed and Debrid-Link named no reason"
	}
	return code
}

// dlHost is one entry of /downloader/hosts.
type dlHost struct {
	Name    string   `json:"name"`
	Type    string   `json:"type"`
	Status  int      `json:"status"`
	Domains []string `json:"domains"`
}

// Hosts asks /downloader/hosts. Only "host" entries with status >= 1 are taken:
// the documentation names that threshold for online, and the other two types
// ("stream", "protect") are not file hosters a download can be routed to.
//
// keys= trims the answer to what is read here - the full one carries a regex
// per host, which is several hundred kilobytes nothing on this side parses.
func (d *DebridLink) Hosts(ctx context.Context) (map[string]bool, error) {
	var hosts []dlHost
	if err := d.get(ctx, "/downloader/hosts?types=host&keys=name,type,status,domains", &hosts); err != nil {
		return nil, err
	}
	set := map[string]bool{}
	for _, h := range hosts {
		if h.Status < 1 {
			continue
		}
		for _, dom := range h.Domains {
			if dom = NormalizeHost(dom); dom != "" {
				set[dom] = true
			}
		}
	}
	return set, nil
}

// dlLink is the link object /downloader/add answers with.
type dlLink struct {
	Name        string `json:"name"`
	DownloadURL string `json:"downloadUrl"`
	Size        int64  `json:"size"`
}

func (d *DebridLink) Unlock(ctx context.Context, link string) (Direct, error) {
	var raw json.RawMessage
	if err := d.postJSON(ctx, "/downloader/add", map[string]string{"url": link}, &raw); err != nil {
		return Direct{}, err
	}
	got, err := firstLink(raw)
	if err != nil {
		return Direct{}, err
	}
	if got.DownloadURL == "" {
		return Direct{}, errors.New("debrid-link: no direct link returned")
	}
	return Direct{URL: got.DownloadURL, Name: got.Name, Size: got.Size}, nil
}

// firstLink reads the one shape the documentation warns about: /downloader/add
// answers the link object itself for an ordinary link, and an ARRAY of them for
// a folder link that expands into several. A single hoster link is one file, so
// the first entry is the answer; decoding the object first means the common
// case never depends on the array branch being right.
func firstLink(raw json.RawMessage) (dlLink, error) {
	var one dlLink
	if err := json.Unmarshal(raw, &one); err == nil {
		return one, nil
	}
	var many []dlLink
	if err := json.Unmarshal(raw, &many); err != nil {
		return dlLink{}, fmt.Errorf("debrid-link: unreadable answer to /downloader/add: %w", err)
	}
	if len(many) == 0 {
		return dlLink{}, errors.New("debrid-link: the link expanded to nothing")
	}
	return many[0], nil
}

// Account reads /account/infos for the plan and /downloader/limits for what is
// left of today's allowance.
//
// premiumLeft is the seconds of premium remaining - the documented sample shows
// 3628800 (42 days) - so it is both the tier test and the expiry, and neither is
// inferred from accountType, whose numbering the documentation never states.
// Guessing that 1 means premium would be exactly the kind of assumption that
// reports a paying account as free.
//
// The traffic half is a PERCENTAGE, not bytes, and is carried as one: Debrid-Link
// meters a daily allowance per hoster (hosters[].daySize) and states one
// account-wide figure, usagePercent {current, value}. Folding per-hoster byte
// caps into a single number would invent a total the service never quotes.
func (d *DebridLink) Account(ctx context.Context) (AccountInfo, error) {
	var acct struct {
		PremiumLeft int64 `json:"premiumLeft"`
	}
	if err := d.get(ctx, "/account/infos", &acct); err != nil {
		return AccountInfo{}, err
	}
	info := AccountInfo{Tier: "free"}
	if acct.PremiumLeft > 0 {
		info.Tier = "premium"
		info.ExpiresAt = time.Now().Add(time.Duration(acct.PremiumLeft) * time.Second).UTC()
	}

	// A failure here must not lose the plan that was just read: the limits call
	// is the extra, the account is the answer.
	var limits struct {
		UsagePercent struct {
			Current float64 `json:"current"`
			Value   float64 `json:"value"`
		} `json:"usagePercent"`
		NextResetSeconds struct {
			Value int64 `json:"value"`
		} `json:"nextResetSeconds"`
	}
	if err := d.get(ctx, "/downloader/limits", &limits); err == nil && limits.UsagePercent.Value > 0 {
		info.Traffic.UsedPercent = limits.UsagePercent.Current / limits.UsagePercent.Value * 100
		info.Traffic.PercentKnown = true
		if limits.NextResetSeconds.Value > 0 {
			info.Traffic.ResetsAt = time.Now().Add(time.Duration(limits.NextResetSeconds.Value) * time.Second).UTC()
		}
	}
	return info, nil
}
