// Regenerates src/components/glyphs.tsx from GlimStone's reference/glyphs.json,
// the list that fixes one drawing per meaning for every GlimStone app. The web
// UI's glyphs come from the same list through web/scripts/gen-glyphs.mjs, under
// the same names.
//
// GlimStone is not a package, so the list is read from a checkout of it:
//
//   node scripts/gen-glyphs.mjs ../../glimstone/reference/glyphs.json
//
// Using another glyph from the list means adding its name to USED and running
// this again.
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '..', 'src', 'components', 'glyphs.tsx');
const source = process.argv[2] ?? join(here, '..', '..', '..', 'glimstone', 'reference', 'glyphs.json');

// In the order the list has them.
const USED = [
  'IconRefresh', 'IconPlay', 'IconStop', 'IconPower', 'IconTrash', 'IconAdd', 'IconClose',
  'IconCopy', 'IconCheck', 'IconLink', 'IconInfo', 'IconBack', 'IconExpand',
  'IconCollapse', 'IconMail', 'IconGear', 'IconFolder', 'IconContainers', 'IconGithub',
  'IconPaste', 'IconMailOpen',
];

const LICENCES = [
  [/^Streamline/, 'Streamline, free Core Solid (https://streamlinehq.com), CC BY 4.0'],
  [/^Font Awesome/, 'Font Awesome Free (https://fontawesome.com), CC BY 4.0'],
  [/^Tabler/, 'Tabler Icons (https://tabler.io/icons), MIT'],
  [/^Material Design Icons/, 'Material Design Icons (https://pictogrammers.com/library/mdi/), Apache 2.0'],
  [/^Simple Icons/, 'Simple Icons (https://simpleicons.org), CC0; the marks are trademarks, used only to name their owner'],
];

const ELEMENTS = { path: 'Path', rect: 'Rect', circle: 'Circle', g: 'G' };
const SHAPES = new Set(['path', 'rect', 'circle']);
const CAMEL = { 'fill-rule': 'fillRule', 'clip-rule': 'clipRule' };

// The list spells markup the SVG way, wrapped in plain <g>s and with paint the
// <Svg> already sets; this turns it into one react-native-svg element per line.
function toJsx(markup, indent) {
  const lines = [];
  const kept = [];
  for (const [, close, tag, attrs, selfClosing] of markup.matchAll(/<(\/?)(\w+)([^>]*?)\s*(\/?)>/g)) {
    const name = ELEMENTS[tag];
    if (!name) throw new Error(`<${tag}> has no react-native-svg element here`);
    const empty = selfClosing || SHAPES.has(tag);
    if (close && SHAPES.has(tag)) continue;
    if (close) {
      if (kept.pop()) lines.push(`${' '.repeat(indent + 2 * kept.filter(Boolean).length)}</${name}>`);
      continue;
    }
    const props = [...attrs.matchAll(/([\w:-]+)="([^"]*)"/g)]
      .filter(([, attr, value]) => !(attr === 'fill' && value === 'currentColor') && attr !== 'stroke-width')
      .map(([, attr, value]) => `${CAMEL[attr] ?? attr}="${value}"`);
    if (tag === 'g' && props.length === 0) {
      kept.push(false);
      continue;
    }
    const pad = ' '.repeat(indent + 2 * kept.filter(Boolean).length);
    lines.push(`${pad}<${[name, ...props].join(' ')}${empty ? ' />' : '>'}`);
    if (!empty) kept.push(true);
  }
  return lines.join('\n');
}

const list = JSON.parse(await readFile(source, 'utf8'));
const byName = new Map(list.map((g) => [g.name, g]));
const glyphs = USED.map((name) => {
  const g = byName.get(name);
  if (!g) throw new Error(`${name} is not in ${source}`);
  return g;
});

const licences = LICENCES.filter(([pattern]) => glyphs.some((g) => pattern.test(g.source))).map(([, text]) => text);

const parts = [
  `// Generated by scripts/gen-glyphs.mjs from GlimStone's reference/glyphs.json.
// Edit the generator or the list, not this file.
//
// Each glyph is GlimStone's drawing for one meaning, a filled shape whose gaps
// are carved with evenodd. The drawings come from:
${licences.map((l) => `//   ${l}`).join('\n')}
// and the rest were drawn for GlimStone or KnightLoader.
import Svg, { Path } from 'react-native-svg';

/**
 * GLYPH_BOX is the box a glyph gets beside a label, in points. Every labelled
 * button here is the key control, where GlimStone sets the glyph at 16 against
 * the 14 of an ordinary button.
 */
export const GLYPH_BOX = 16;

/**
 * GLYPH_INK is how much of its box a glyph's ink fills on its longer side. Air
 * around the ink keeps a glyph off the edge of the badge it sits in.
 */
export const GLYPH_INK = 0.8;

export interface GlyphProps {
  color: string;
  /** The box in points, or a share of the parent such as '100%'. */
  size?: number | string;
  /** Ink to the edge of the box, for a mark box that sizes its artwork to its
   *  own edges, as the README buttons do. */
  tight?: boolean;
}

// The list crops each viewBox square to the glyph's ink, so widening it around
// its centre leaves every glyph the same share of its box, whatever its grid.
function frame(viewBox: string, tight?: boolean): string {
  if (tight) return viewBox;
  const [x, y, side] = viewBox.split(' ').map(Number);
  const pad = (side / GLYPH_INK - side) / 2;
  return [x - pad, y - pad, side + 2 * pad, side + 2 * pad].join(' ');
}
`,
];

for (const g of glyphs) {
  parts.push(`/** ${g.means}: ${g.source}. */
export function ${g.name}({ color, size = GLYPH_BOX, tight }: GlyphProps) {
  return (
    <Svg width={size} height={size} viewBox={frame('${g.viewBox}', tight)} fill={color}>
${toJsx(g.svg, 6)}
    </Svg>
  );
}
`);
}

const text = parts.join('\n');
const elements = [...new Set([...text.matchAll(/<(G|Rect|Circle|Path)\b/g)].map(([, name]) => name))].sort();

await writeFile(out, text.replace('{ Path }', `{ ${elements.join(', ')} }`));
console.log(`wrote ${glyphs.length} glyphs to ${out}`);
